//
// KariAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class KariAPI {
    /**
     Get Kari Information.
     - parameter identifier: (path) Identifier of Kari to return 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getKari(identifier: String, completion: @escaping ((_ data: Kari?,_ error: Error?) -> Void)) {
        getKariWithRequestBuilder(identifier: identifier).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get Kari Information.
     - GET /kari/kari/{identifier}
     - parameter identifier: (path) Identifier of Kari to return 

     - returns: RequestBuilder<Kari> 
     */
    open class func getKariWithRequestBuilder(identifier: String) -> RequestBuilder<Kari> {
        var path = "/kari/kari/{identifier}"
        let identifierPreEscape = "\(identifier)"
        let identifierPostEscape = identifierPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{identifier}", with: identifierPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Kari>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
